/**
 * Catálogo funcional do AGRO365, normalizado a partir do mapeamento de 16/08/2026.
 *
 * Esta é a fonte única da esteira de protótipo: cada item tem um responsável,
 * uma rota e o nível de fidelidade permitido pela evidência disponível.
 * `mapped` significa que a gravação mostrou apenas o acesso ou parte do fluxo;
 * quando uma jornada precisa ser demonstrável sem campos observados, as premissas mínimas
 * ficam identificadas em `sourceDetail` para revisão posterior com o especialista de domínio.
 */
export type FeatureStatus = 'ready' | 'mapped' | 'hardware'
export type FeatureFieldType = 'text' | 'number' | 'date' | 'select' | 'textarea'
export type HardwareSimulationKind = 'devices' | 'scale' | 'rfid' | 'scanner'

export interface FeatureField {
  id: string
  label: string
  type?: FeatureFieldType
  required?: boolean
  placeholder?: string
  options?: string[]
}

export interface FeatureDefinition {
  id: string
  group: string
  title: string
  objective: string
  status: FeatureStatus
  existingRoute?: string
  fields?: FeatureField[]
  sections?: string[]
  capabilities?: string[]
  primaryAction?: string
  emptyLabel?: string
  sourceDetail?: string
  /** ativa a jornada lista → formulário → sucesso → detalhe. */
  listMode?: boolean
  /** permite que uma consulta administrativa leia os registros de outra função. */
  dataSourceId?: string
  createAction?: string
  recordTitleField?: string
  recordDescriptionFields?: string[]
  simulation?: HardwareSimulationKind
  simulationTargetField?: string
  successTitle?: string
  successDescription?: string
  auditExport?: 'estoque' | 'pecuaria'
}

const responsavel: FeatureField = {
  id: 'responsavel',
  label: 'Responsável',
  type: 'select',
  required: true,
  options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
}

export const ADMIN_FEATURES: FeatureDefinition[] = [
  {
    id: 'painel-financeiro',
    group: 'Painéis de decisão',
    title: 'Financeiro e operacional',
    objective: 'Consolidar resultados financeiros, custos e produção por período.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/financeiro',
  },
  {
    id: 'painel-pecuario',
    group: 'Painéis de decisão',
    title: 'Dashboard pecuário',
    objective: 'Acompanhar estoque atual e desempenho do rebanho.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/pecuaria',
  },
  {
    id: 'lotacao-currais',
    group: 'Painéis de decisão',
    title: 'Lotação de currais',
    objective: 'Supervisionar ocupação, capacidade e alertas dos currais.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/confinamento',
  },
  {
    id: 'ativos',
    group: 'Painéis de decisão',
    title: 'Ativos e depreciação',
    objective: 'Acompanhar patrimônio, manutenção e valor residual.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/ativos',
  },
  {
    id: 'suprimentos',
    group: 'Painéis de decisão',
    title: 'Suprimentos',
    objective: 'Comparar cotações e apoiar decisões de compra.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/suprimentos',
  },
  {
    id: 'analise-uso',
    group: 'Painéis de decisão',
    title: 'Análise de uso',
    objective: 'Supervisionar usuários ativos e utilização por fazenda.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/uso',
  },
  {
    id: 'consultas-gerenciais',
    group: 'Consultas e auditoria',
    title: 'Consultas gerenciais',
    objective: 'Consultar lotes, estoque e pesagens sem permitir alterações.',
    status: 'ready',
    existingRoute: '/fazendas/dashboards/consultas',
  },
  {
    id: 'areas',
    group: 'Consultas e auditoria',
    title: 'Áreas cadastradas',
    objective: 'Consultar as áreas usadas pelos processos da fazenda.',
    status: 'ready',
    listMode: true,
    dataSourceId: 'cadastrar-area',
    emptyLabel: 'Nenhuma área encontrada para os filtros atuais.',
    sourceDetail: 'A consulta usa os mesmos registros criados no ambiente operacional.',
  },
  {
    id: 'saldo-estoque',
    group: 'Consultas e auditoria',
    title: 'Saldo de estoque',
    objective: 'Consultar o saldo disponível dos itens armazenados.',
    status: 'ready',
    listMode: true,
    emptyLabel: 'Nenhum item de estoque encontrado.',
    sourceDetail: 'Consulta demonstrativa consolidada por item e local de armazenamento.',
  },
  {
    id: 'processamentos',
    group: 'Consultas e auditoria',
    title: 'Processamentos pecuários',
    objective: 'Acompanhar rotinas pendentes e concluídas.',
    status: 'ready',
    listMode: true,
    sections: ['Pendentes', 'Concluídos'],
    emptyLabel: 'Nenhum processamento pendente.',
  },
  {
    id: 'exportar-log-estoque',
    group: 'Consultas e auditoria',
    title: 'Exportar log de estoque',
    objective: 'Exportar registros de auditoria relacionados ao estoque.',
    status: 'ready',
    auditExport: 'estoque',
    sourceDetail: 'Período e formatos CSV/JSON são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'exportar-log-pecuaria',
    group: 'Consultas e auditoria',
    title: 'Exportar log da pecuária',
    objective: 'Exportar o histórico de eventos e movimentações do rebanho.',
    status: 'ready',
    auditExport: 'pecuaria',
    sourceDetail: 'Período e formatos CSV/JSON são premissas funcionais do protótipo frontend.',
  },
]

export const OPERATIONAL_FEATURES: FeatureDefinition[] = [
  {
    id: 'cadastrar-area',
    group: 'Cadastros',
    title: 'Áreas',
    objective: 'Cadastrar áreas usadas nos processos da fazenda.',
    status: 'ready',
    listMode: true,
    fields: [
      { id: 'nome', label: 'Nome da área', required: true, placeholder: 'Ex.: Talhão 03' },
      { id: 'tipo', label: 'Tipo de uso', type: 'select', required: true, options: ['Agricultura', 'Pecuária', 'Fruticultura', 'Reserva'] },
      { id: 'area-total', label: 'Área total', type: 'number', required: true },
      { id: 'unidade', label: 'Unidade', type: 'select', required: true, options: ['ha', 'm²'] },
      { id: 'localizacao', label: 'Localização', required: true, placeholder: 'Setor ou referência' },
      { id: 'cultura', label: 'Cultura / cobertura', placeholder: 'Opcional' },
      { id: 'observacao', label: 'Observação', type: 'textarea', placeholder: 'Informações adicionais' },
    ],
    createAction: 'Adicionar área',
    primaryAction: 'Salvar área',
    recordTitleField: 'nome',
    recordDescriptionFields: ['tipo', 'area-total', 'unidade'],
  },
  {
    id: 'formulacoes',
    group: 'Estoque',
    title: 'Formulações',
    objective: 'Criar formulações compostas por matérias-primas e percentuais.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'ativo', label: 'Ativo', type: 'select', required: true, options: ['Sim', 'Não'] },
      { id: 'produto', label: 'Produto', required: true, placeholder: 'Selecione ou busque o produto' },
      { id: 'quantidade', label: 'Quantidade de referência', type: 'number', required: true },
      { id: 'unidade', label: 'Unidade de medida', type: 'select', required: true, options: ['kg', 't', 'L'] },
      { id: 'tipo', label: 'Tipo', type: 'select', required: true, options: ['Estoque', 'Formulação'] },
      { id: 'materia-prima', label: 'Matéria-prima', required: true },
      { id: 'porcentagem', label: 'Porcentagem (%)', type: 'number', required: true },
    ],
    sections: ['Matérias-primas'],
    primaryAction: 'Salvar formulação',
    createAction: 'Nova formulação',
    recordTitleField: 'produto',
    recordDescriptionFields: ['quantidade', 'unidade', 'ativo'],
  },
  {
    id: 'batidas',
    group: 'Estoque',
    title: 'Batida',
    objective: 'Registrar a produção de uma formulação para um armazém de destino.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'tipo', label: 'Tipo', type: 'select', required: true, options: ['Estoque', 'Formulação'] },
      { id: 'armazem', label: 'Armazém de destino', type: 'select', required: true, options: ['Armazém A', 'Depósito B', 'Farmácia'] },
      { id: 'produto', label: 'Produto', required: true },
      { id: 'quantidade', label: 'Quantidade de referência', type: 'number', required: true },
      { id: 'unidade', label: 'Unidade de medida', type: 'select', required: true, options: ['kg', 't', 'L'] },
    ],
    primaryAction: 'Salvar batida',
    createAction: 'Nova batida',
    recordTitleField: 'produto',
    recordDescriptionFields: ['quantidade', 'unidade', 'armazem'],
    emptyLabel: 'Nenhuma batida registrada.',
  },
  {
    id: 'conexao-aparelhos',
    group: 'Misturador',
    title: 'Conexão de aparelhos',
    objective: 'Conectar balança e equipamentos externos por Bluetooth.',
    status: 'hardware',
    capabilities: ['Bluetooth', 'Localização', 'Busca de dispositivos', 'Permissão durante o uso'],
    simulation: 'devices',
    primaryAction: 'Concluir configuração',
    successTitle: 'Aparelhos conectados no protótipo',
    successDescription: 'A balança e o equipamento externo estão disponíveis para os fluxos simulados desta sessão.',
  },
  {
    id: 'carga',
    group: 'Misturador',
    title: 'Carga',
    objective: 'Executar o fluxo operacional de carregamento do misturador.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'formulacao', label: 'Formulação / produto', required: true },
      { id: 'origem', label: 'Armazém de origem', required: true },
      { id: 'equipamento', label: 'Misturador / equipamento', required: true },
      { id: 'quantidade', label: 'Quantidade', type: 'number', required: true },
      { id: 'unidade', label: 'Unidade', type: 'select', required: true, options: ['kg', 't'] },
    ],
    createAction: 'Nova carga',
    primaryAction: 'Registrar carga',
    recordTitleField: 'formulacao',
    recordDescriptionFields: ['quantidade', 'unidade', 'equipamento'],
    sourceDetail: 'A fonte mostrou apenas a entrada; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'descarga',
    group: 'Misturador',
    title: 'Descarga',
    objective: 'Executar o fluxo operacional de descarga do misturador.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'produto', label: 'Produto carregado', required: true },
      { id: 'destino', label: 'Área / cocho de destino', required: true },
      { id: 'equipamento', label: 'Misturador / equipamento', required: true },
      { id: 'quantidade', label: 'Quantidade descarregada', type: 'number', required: true },
      { id: 'unidade', label: 'Unidade', type: 'select', required: true, options: ['kg', 't'] },
    ],
    createAction: 'Nova descarga',
    primaryAction: 'Registrar descarga',
    recordTitleField: 'destino',
    recordDescriptionFields: ['produto', 'quantidade', 'unidade'],
    sourceDetail: 'A fonte mostrou apenas a entrada; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'balanca',
    group: 'Misturador',
    title: 'Balança',
    objective: 'Obter dados de pesagem do equipamento conectado.',
    status: 'hardware',
    capabilities: ['Bluetooth', 'Balança'],
    simulation: 'scale',
    primaryAction: 'Confirmar leitura',
    successTitle: 'Leitura de balança confirmada',
    successDescription: 'O peso simulado foi capturado e pode ser usado na apresentação do fluxo.',
  },
  {
    id: 'nota-cocho',
    group: 'Misturador',
    title: 'Nota de cocho',
    objective: 'Registrar e consultar a nota de cocho.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data', type: 'date', required: true },
      { id: 'lote', label: 'Lote / curral', required: true },
      { id: 'nota', label: 'Nota de cocho', type: 'select', required: true, options: ['0 — Limpo', '1 — Baixo', '2 — Adequado', '3 — Sobra moderada', '4 — Sobra alta'] },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    createAction: 'Nova nota de cocho',
    primaryAction: 'Salvar nota',
    recordTitleField: 'lote',
    recordDescriptionFields: ['nota', 'data'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'configuracoes-misturador',
    group: 'Misturador',
    title: 'Configurações',
    objective: 'Parametrizar recursos do misturador.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'nome', label: 'Nome da configuração', required: true },
      { id: 'unidade', label: 'Unidade padrão', type: 'select', required: true, options: ['kg', 't'] },
      { id: 'tolerancia', label: 'Tolerância de pesagem (%)', type: 'number', required: true },
      { id: 'alerta', label: 'Alertas sonoros', type: 'select', required: true, options: ['Ativados', 'Desativados'] },
    ],
    createAction: 'Nova configuração',
    primaryAction: 'Salvar configuração',
    recordTitleField: 'nome',
    recordDescriptionFields: ['unidade', 'tolerancia', 'alerta'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os parâmetros são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'apontamento',
    group: 'Agricultura',
    title: 'Apontamento agrícola',
    objective: 'Registrar uma operação agrícola e os recursos associados.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'area', label: 'Área', type: 'select', required: true, options: ['Talhão 01', 'Talhão 02', 'Pasto Norte'] },
      { id: 'operacao', label: 'Operação', required: true },
      { id: 'atividade', label: 'Atividade', required: true },
      { id: 'area-total', label: 'Área total', type: 'number', required: true },
      { id: 'area-utilizada', label: 'Área utilizada', type: 'number', required: true },
      { id: 'armazem-insumo', label: 'Armazém de insumo', type: 'select', options: ['Armazém A', 'Depósito B'] },
      { id: 'armazem-producao', label: 'Armazém de produção', type: 'select', required: true, options: ['Armazém A', 'Depósito B'] },
    ],
    sections: ['Insumos', 'Abastecimentos', 'Máquinas / Implementos', 'Mão de obra / Serviços', 'Ocorrências', 'Produção'],
    primaryAction: 'Salvar apontamento',
    createAction: 'Novo apontamento',
    recordTitleField: 'atividade',
    recordDescriptionFields: ['operacao', 'area', 'area-utilizada'],
  },
  {
    id: 'marcacao',
    group: 'Agricultura',
    title: 'Marcação',
    objective: 'Acessar e registrar marcações agrícolas.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'area', label: 'Área', required: true },
      { id: 'tipo', label: 'Tipo de marcação', type: 'select', required: true, options: ['Ponto de atenção', 'Amostragem', 'Ocorrência', 'Limite de operação'] },
      { id: 'descricao', label: 'Descrição', required: true },
      { id: 'referencia', label: 'Referência de localização', required: true },
    ],
    createAction: 'Nova marcação',
    primaryAction: 'Salvar marcação',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['tipo', 'area', 'referencia'],
    sourceDetail: 'Os campos não foram exibidos; o protótipo usa premissas mínimas sem GPS real.',
  },
  {
    id: 'colheita-frutas',
    group: 'Agricultura',
    title: 'Colheita de frutas',
    objective: 'Registrar motorista, veículo e caixas da colheita.',
    status: 'ready',
    fields: [
      { id: 'placa', label: 'Placa', required: true },
      { id: 'motorista', label: 'Motorista', required: true },
      { id: 'cpf', label: 'CPF do motorista', required: true },
      { id: 'caixas', label: 'Caixas (kg)', type: 'number', required: true },
    ],
    sections: ['Caixas da colheita'],
    primaryAction: 'Registrar colheita',
  },
  {
    id: 'rebanho-inicial',
    group: 'Pecuária',
    title: 'Rebanho inicial',
    objective: 'Estabelecer a composição inicial do rebanho.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data de referência', type: 'date', required: true },
      { id: 'especie', label: 'Espécie', type: 'select', required: true, options: ['Bovino', 'Bubalino', 'Ovino'] },
      { id: 'categoria', label: 'Categoria', type: 'select', required: true, options: ['Bezerro', 'Novilha', 'Vaca', 'Boi'] },
      { id: 'quantidade', label: 'Quantidade de animais', type: 'number', required: true },
      { id: 'area', label: 'Área / módulo inicial', required: true },
      { id: 'peso-medio', label: 'Peso médio (kg)', type: 'number' },
    ],
    createAction: 'Nova composição inicial',
    primaryAction: 'Cadastrar rebanho',
    recordTitleField: 'categoria',
    recordDescriptionFields: ['quantidade', 'especie', 'area'],
    sourceDetail: 'Os campos internos não foram exibidos; o protótipo usa a composição mínima necessária para iniciar o rebanho.',
  },
  {
    id: 'conexao-aparelhos-pecuaria',
    group: 'Pecuária',
    title: 'Conexão de aparelhos',
    objective: 'Preparar balança e leitor RFID para as rotinas pecuárias.',
    status: 'hardware',
    capabilities: ['Bluetooth', 'Localização', 'Balança', 'RFID'],
    simulation: 'devices',
    primaryAction: 'Concluir configuração',
    successTitle: 'Aparelhos pecuários conectados',
    successDescription: 'A balança e o leitor RFID estão conectados na simulação desta sessão.',
  },
  {
    id: 'lote-animais',
    group: 'Pecuária',
    title: 'Lote de animais',
    objective: 'Criar um lote em fluxo de múltiplas etapas.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'especie', label: 'Espécie', type: 'select', required: true, options: ['Bovino', 'Bubalino', 'Ovino'] },
      { id: 'descricao', label: 'Descrição', required: true },
      { id: 'categoria', label: 'Categoria', type: 'select', required: true, options: ['Bezerro', 'Novilha', 'Vaca', 'Boi'] },
    ],
    createAction: 'Novo lote',
    primaryAction: 'Criar lote',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['especie', 'categoria'],
  },
  {
    id: 'registrar-animal',
    group: 'Pecuária',
    title: 'Registrar animal',
    objective: 'Cadastrar um animal individualmente.',
    status: 'ready',
    listMode: true,
    fields: [
      { id: 'categoria', label: 'Categoria', required: true },
      { id: 'raca', label: 'Raça', required: true },
      { id: 'nascimento', label: 'Data de nascimento', type: 'date', required: true },
      { id: 'peso', label: 'Peso (kg)', type: 'number', required: true },
      { id: 'preco-kg', label: 'Preço do kg vivo', type: 'number' },
    ],
    createAction: 'Novo animal',
    primaryAction: 'Registrar animal',
    recordTitleField: 'categoria',
    recordDescriptionFields: ['raca', 'peso', 'nascimento'],
  },
  {
    id: 'pesagem',
    group: 'Pecuária',
    title: 'Pesagens',
    objective: 'Consultar e registrar pesagens do rebanho.',
    status: 'ready',
    existingRoute: '/fazendas/campo/pesagem',
  },
  {
    id: 'transferencia-animal',
    group: 'Pecuária',
    title: 'Transferência animal / lote',
    objective: 'Mover um animal para outro lote com identificação por brinco, RFID ou câmera.',
    status: 'hardware',
    listMode: true,
    simulation: 'rfid',
    simulationTargetField: 'identificacao',
    fields: [
      { id: 'identificacao', label: 'Identificação animal', required: true, placeholder: 'Brinco ou ID' },
      responsavel,
      { id: 'lote-atual', label: 'Lote atual', required: true },
      { id: 'novo-lote', label: 'Novo lote', required: true },
    ],
    capabilities: ['Balança', 'RFID', 'Scanner SISBOV'],
    createAction: 'Nova transferência de animal',
    primaryAction: 'Salvar transferência',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['lote-atual', 'novo-lote'],
  },
  {
    id: 'scanner-sisbov',
    group: 'Pecuária',
    title: 'Scanner SISBOV',
    objective: 'Capturar a identificação do animal usando a câmera.',
    status: 'hardware',
    capabilities: ['Câmera', 'Área de enquadramento', 'Reiniciar leitura'],
    simulation: 'scanner',
    primaryAction: 'Usar identificação capturada',
    successTitle: 'Identificação SISBOV capturada',
    successDescription: 'O código simulado está disponível para identificação do animal nesta sessão.',
  },
  {
    id: 'transferencia-lote-area',
    group: 'Pecuária',
    title: 'Transferência lote / área',
    objective: 'Alterar a localização de um lote entre área e módulo.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'lote', label: 'Lote', required: true },
      { id: 'local-atual', label: 'Área / módulo atual', required: true },
      { id: 'area', label: 'Nova área', required: true },
      { id: 'modulo', label: 'Novo módulo', required: true },
    ],
    createAction: 'Nova transferência',
    primaryAction: 'Salvar transferência',
    recordTitleField: 'lote',
    recordDescriptionFields: ['area', 'modulo'],
  },
  {
    id: 'nascimentos',
    group: 'Pecuária',
    title: 'Nascimentos',
    objective: 'Registrar nascimento de animais.',
    status: 'ready',
    existingRoute: '/fazendas/campo/ciclo',
  },
  {
    id: 'mortes',
    group: 'Pecuária',
    title: 'Mortes',
    objective: 'Consultar e registrar mortes do rebanho.',
    status: 'ready',
    existingRoute: '/fazendas/campo/ciclo',
  },
  {
    id: 'perdas',
    group: 'Pecuária',
    title: 'Perdas',
    objective: 'Registrar perdas após identificar o animal.',
    status: 'hardware',
    listMode: true,
    simulation: 'rfid',
    simulationTargetField: 'identificacao',
    fields: [
      { id: 'identificacao', label: 'Identificação animal', required: true, placeholder: 'Brinco ou ID' },
      responsavel,
      { id: 'data', label: 'Data da ocorrência', type: 'date', required: true },
      { id: 'lote', label: 'Lote atual', required: true },
      { id: 'causa', label: 'Motivo da perda', required: true },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    capabilities: ['Balança', 'RFID', 'Scanner SISBOV'],
    createAction: 'Nova perda',
    primaryAction: 'Registrar perda',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['causa', 'lote', 'data'],
    sourceDetail: 'A fonte mostrou apenas a identificação; os campos posteriores são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'compras-animais',
    group: 'Pecuária',
    title: 'Compra de animais',
    objective: 'Consultar e registrar compras de animais.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'fornecedor', label: 'Fornecedor', required: true },
      { id: 'data', label: 'Data da compra', type: 'date', required: true },
      { id: 'especie', label: 'Espécie', type: 'select', required: true, options: ['Bovino', 'Bubalino', 'Ovino'] },
      { id: 'categoria', label: 'Categoria', required: true },
      { id: 'quantidade', label: 'Quantidade de animais', type: 'number', required: true },
      { id: 'valor-total', label: 'Valor total (R$)', type: 'number', required: true },
      { id: 'documento', label: 'Nota / documento de origem', required: true },
    ],
    createAction: 'Nova compra',
    primaryAction: 'Registrar compra',
    recordTitleField: 'fornecedor',
    recordDescriptionFields: ['quantidade', 'categoria', 'data'],
    emptyLabel: 'Nenhuma compra de animais registrada.',
    sourceDetail: 'O formulário não foi aberto; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'vendas',
    group: 'Pecuária',
    title: 'Vendas',
    objective: 'Registrar vendas de animais com documentos e frete.',
    status: 'ready',
    existingRoute: '/fazendas/campo/venda',
  },
  {
    id: 'nutricoes',
    group: 'Pecuária',
    title: 'Nutrições',
    objective: 'Registrar produtos, quantidade, área, módulo e cocho.',
    status: 'ready',
    existingRoute: '/fazendas/campo/arracoamento',
  },
  {
    id: 'sanitario',
    group: 'Pecuária',
    title: 'Sanitário',
    objective: 'Criar um manejo sanitário por responsável e lote.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'lote', label: 'Lote', required: true },
      { id: 'data', label: 'Data do manejo', type: 'date', required: true },
      { id: 'tipo', label: 'Tipo de manejo', type: 'select', required: true, options: ['Vacinação', 'Vermifugação', 'Tratamento', 'Exame'] },
      { id: 'produto', label: 'Produto / procedimento', required: true },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    createAction: 'Novo manejo sanitário',
    primaryAction: 'Salvar manejo',
    recordTitleField: 'lote',
    recordDescriptionFields: ['tipo', 'data'],
    sourceDetail: 'A fonte mostrou apenas a primeira etapa; os campos complementares são premissas do protótipo frontend.',
  },
  {
    id: 'desmama',
    group: 'Pecuária',
    title: 'Desmama',
    objective: 'Registrar desmama e identificar vacas paridas.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'tipo', label: 'Tipo', type: 'select', required: true, options: ['Convencional', 'Precoce', 'Temporária'] },
      { id: 'lote', label: 'Lote', required: true },
      { id: 'identificacao', label: 'Identificação das vacas paridas', required: true },
    ],
    sections: ['Identificações adicionais'],
    createAction: 'Nova desmama',
    primaryAction: 'Salvar desmama',
    recordTitleField: 'lote',
    recordDescriptionFields: ['tipo', 'identificacao'],
  },
  {
    id: 'apartacao',
    group: 'Pecuária',
    title: 'Apartação',
    objective: 'Executar e registrar a apartação do rebanho.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data', type: 'date', required: true },
      { id: 'lote-origem', label: 'Lote de origem', required: true },
      { id: 'criterio', label: 'Critério', type: 'select', required: true, options: ['Peso', 'Categoria', 'Sexo', 'Condição corporal'] },
      { id: 'lote-destino', label: 'Lote de destino', required: true },
      { id: 'quantidade', label: 'Quantidade de animais', type: 'number', required: true },
    ],
    createAction: 'Nova apartação',
    primaryAction: 'Registrar apartação',
    recordTitleField: 'lote-origem',
    recordDescriptionFields: ['criterio', 'lote-destino', 'quantidade'],
    sourceDetail: 'Os campos não foram exibidos; o protótipo usa premissas operacionais mínimas.',
  },
  {
    id: 'localizar-animal',
    group: 'Pecuária',
    title: 'Localizar animal',
    objective: 'Localizar um animal por brinco, ID, RFID ou câmera.',
    status: 'hardware',
    fields: [{ id: 'identificacao', label: 'Identificação animal', required: true, placeholder: 'Brinco ou ID' }],
    capabilities: ['RFID', 'Scanner SISBOV'],
    simulation: 'rfid',
    simulationTargetField: 'identificacao',
    primaryAction: 'Buscar animal',
    successTitle: 'Animal localizado',
    successDescription: 'Animal ativo no Lote 42 · Engorda, atualmente no Pasto Norte · Módulo A.',
  },
  {
    id: 'pastagens',
    group: 'Pecuária',
    title: 'Pastagens',
    objective: 'Registrar recursos e serviços aplicados à pastagem.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'armazem-insumos', label: 'Armazém de insumos', required: true },
      { id: 'armazem-producao', label: 'Armazém de produção', required: true },
    ],
    sections: ['Insumos', 'Abastecimentos', 'Máquinas / Equipamentos'],
    createAction: 'Novo manejo de pastagem',
    primaryAction: 'Salvar pastagem',
    recordTitleField: 'armazem-producao',
    recordDescriptionFields: ['armazem-insumos', 'responsavel'],
  },
  {
    id: 'estacao-monta',
    group: 'Reprodução',
    title: 'Estação de monta',
    objective: 'Gerenciar períodos e ciclos de reprodução.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'nome', label: 'Nome da estação', required: true },
      { id: 'inicio', label: 'Data de início', type: 'date', required: true },
      { id: 'fim', label: 'Data de término', type: 'date', required: true },
      { id: 'metodo', label: 'Método principal', type: 'select', required: true, options: ['Monta natural', 'Inseminação artificial', 'IATF', 'Transferência de embrião'] },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    createAction: 'Nova estação',
    primaryAction: 'Criar estação',
    recordTitleField: 'nome',
    recordDescriptionFields: ['metodo', 'inicio', 'fim'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'lotes-reproducao',
    group: 'Reprodução',
    title: 'Lotes / reprodução',
    objective: 'Organizar lotes vinculados ao processo reprodutivo.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'estacao', label: 'Estação de monta', required: true },
      { id: 'lote', label: 'Lote', required: true },
      { id: 'finalidade', label: 'Finalidade', type: 'select', required: true, options: ['Matrizes', 'Reprodutores', 'Receptoras', 'Novilhas'] },
      { id: 'quantidade', label: 'Quantidade de animais', type: 'number', required: true },
    ],
    createAction: 'Vincular lote',
    primaryAction: 'Salvar vínculo',
    recordTitleField: 'lote',
    recordDescriptionFields: ['finalidade', 'estacao', 'quantidade'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'material-reprodutivo',
    group: 'Reprodução',
    title: 'Touros / sêmen / embrião',
    objective: 'Gerenciar material e recursos reprodutivos.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'tipo', label: 'Tipo de recurso', type: 'select', required: true, options: ['Touro', 'Sêmen', 'Embrião'] },
      { id: 'identificacao', label: 'Identificação / código', required: true },
      { id: 'raca', label: 'Raça', required: true },
      { id: 'fornecedor', label: 'Fornecedor / origem', required: true },
      { id: 'quantidade', label: 'Quantidade disponível', type: 'number', required: true },
    ],
    createAction: 'Novo recurso',
    primaryAction: 'Cadastrar recurso',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['tipo', 'raca', 'quantidade'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'protocolos-estacao',
    group: 'Reprodução',
    title: 'Protocolos / estação',
    objective: 'Gerenciar protocolos associados à estação reprodutiva.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'nome', label: 'Nome do protocolo', required: true },
      { id: 'estacao', label: 'Estação de monta', required: true },
      { id: 'tipo', label: 'Tipo', type: 'select', required: true, options: ['IATF', 'Inseminação', 'Transferência de embrião', 'Sincronização de cio'] },
      { id: 'inicio', label: 'Data de início', type: 'date', required: true },
    ],
    sections: ['Etapas do protocolo'],
    createAction: 'Novo protocolo',
    primaryAction: 'Salvar protocolo',
    recordTitleField: 'nome',
    recordDescriptionFields: ['tipo', 'estacao', 'inicio'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'monta-natural',
    group: 'Reprodução',
    title: 'Monta natural',
    objective: 'Registrar operações de monta natural.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data', type: 'date', required: true },
      { id: 'lote', label: 'Lote de matrizes', required: true },
      { id: 'touro', label: 'Touro / reprodutor', required: true },
      { id: 'quantidade', label: 'Quantidade de fêmeas', type: 'number', required: true },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    createAction: 'Nova monta',
    primaryAction: 'Registrar monta',
    recordTitleField: 'lote',
    recordDescriptionFields: ['touro', 'quantidade', 'data'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'diagnostico-gestacao',
    group: 'Reprodução',
    title: 'Diagnóstico de gestação',
    objective: 'Registrar e consultar diagnósticos de gestação.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data do diagnóstico', type: 'date', required: true },
      { id: 'lote', label: 'Lote', required: true },
      { id: 'resultado', label: 'Resultado', type: 'select', required: true, options: ['Prenhe', 'Vazia', 'Reavaliar'] },
      { id: 'quantidade', label: 'Quantidade de animais', type: 'number', required: true },
      { id: 'veterinario', label: 'Veterinário responsável', required: true },
    ],
    createAction: 'Novo diagnóstico',
    primaryAction: 'Salvar diagnóstico',
    recordTitleField: 'lote',
    recordDescriptionFields: ['resultado', 'quantidade', 'data'],
    sourceDetail: 'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
  },
  {
    id: 'abastecimentos',
    group: 'Gestão de frota',
    title: 'Abastecimentos',
    objective: 'Consultar e registrar abastecimentos da frota.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'data', label: 'Data', type: 'date', required: true },
      { id: 'veiculo', label: 'Veículo / equipamento', type: 'select', required: true, options: ['Trator John Deere 6110', 'Colheitadeira CR7', 'Caminhão Boiadeiro', 'Pulverizador'] },
      { id: 'combustivel', label: 'Combustível', type: 'select', required: true, options: ['Diesel S10', 'Diesel S500', 'Gasolina', 'Etanol'] },
      { id: 'quantidade', label: 'Quantidade (L)', type: 'number', required: true },
      { id: 'medidor', label: 'Hodômetro / horímetro', type: 'number', required: true },
      { id: 'origem', label: 'Posto / tanque de origem', required: true },
    ],
    createAction: 'Novo abastecimento',
    primaryAction: 'Registrar abastecimento',
    recordTitleField: 'veiculo',
    recordDescriptionFields: ['quantidade', 'combustivel', 'data'],
    emptyLabel: 'Nenhum abastecimento registrado.',
    sourceDetail: 'Campos complementares adotados como premissa funcional do protótipo frontend.',
  },
  {
    id: 'manutencao-frota',
    group: 'Gestão de frota',
    title: 'Manutenção',
    objective: 'Controlar manutenções da frota.',
    status: 'ready',
    listMode: true,
    fields: [
      responsavel,
      { id: 'equipamento', label: 'Veículo / equipamento', type: 'select', required: true, options: ['Trator John Deere 6110', 'Colheitadeira CR7', 'Caminhão Boiadeiro', 'Pulverizador'] },
      { id: 'tipo', label: 'Tipo', type: 'select', required: true, options: ['Preventiva', 'Corretiva', 'Inspeção'] },
      { id: 'descricao', label: 'Serviço', required: true, placeholder: 'Descreva a manutenção' },
      { id: 'data', label: 'Data prevista', type: 'date', required: true },
      { id: 'oficina', label: 'Oficina / responsável externo', required: true },
      { id: 'custo', label: 'Custo estimado (R$)', type: 'number' },
      { id: 'observacao', label: 'Observação', type: 'textarea' },
    ],
    createAction: 'Nova manutenção',
    primaryAction: 'Programar manutenção',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['tipo', 'equipamento', 'data'],
  },
  {
    id: 'minhas-os',
    group: 'Ordem de serviço',
    title: 'Minhas OS',
    objective: 'Consultar ordens de serviço vinculadas ao funcionário e à fazenda.',
    status: 'ready',
    listMode: true,
    emptyLabel: 'Nenhuma ordem de serviço atribuída.',
    sourceDetail: 'Consulta demonstrativa das ordens atribuídas ao funcionário e à fazenda ativa.',
  },
  {
    id: 'sincronizacao',
    group: 'Sincronização',
    title: 'Sincronização de dados',
    objective: 'Enviar a fila local para a nuvem após operação offline.',
    status: 'ready',
    existingRoute: '/fazendas/mais/sync',
    capabilities: ['Rebanho', 'Lotes', 'Pesagem', 'Mortes'],
  },
]

export const FEATURE_BY_ID: Record<string, FeatureDefinition> = Object.fromEntries(
  [...ADMIN_FEATURES, ...OPERATIONAL_FEATURES].map((feature) => [feature.id, feature]),
)

export function groupFeatures(features: FeatureDefinition[]) {
  return features.reduce<Record<string, FeatureDefinition[]>>((groups, feature) => {
    groups[feature.group] = [...(groups[feature.group] ?? []), feature]
    return groups
  }, {})
}
