// Fonte funcional Flutter do AGRO365.
//
// Portado mecanicamente em 16/08/2026 do catálogo React congelado no commit
// 960fe54. A partir da M1, mudanças funcionais entram primeiro neste contrato
// Dart; o catálogo React permanece apenas como evidência histórica até M13.

enum FeatureProfile { administration, operational }

enum FeatureStatus { ready, mapped, hardware }

enum FeatureFieldType { text, number, date, select, textarea }

enum HardwareSimulationKind { devices, scale, rfid, scanner }

enum AuditExportKind { estoque, pecuaria }

class FeatureField {
  const FeatureField({
    required this.id,
    required this.label,
    this.type,
    this.isRequired = false,
    this.placeholder,
    this.options = const [],
  });

  final String id;
  final String label;
  final FeatureFieldType? type;
  final bool isRequired;
  final String? placeholder;
  final List<String> options;
}

class FeatureDefinition {
  const FeatureDefinition({
    required this.id,
    required this.profile,
    required this.group,
    required this.title,
    required this.objective,
    required this.status,
    this.existingRoute,
    this.fields = const [],
    this.sections = const [],
    this.capabilities = const [],
    this.primaryAction,
    this.emptyLabel,
    this.sourceDetail,
    this.listMode = false,
    this.dataSourceId,
    this.createAction,
    this.recordTitleField,
    this.recordDescriptionFields = const [],
    this.simulation,
    this.simulationTargetField,
    this.successTitle,
    this.successDescription,
    this.auditExport,
  });

  final String id;
  final FeatureProfile profile;
  final String group;
  final String title;
  final String objective;
  final FeatureStatus status;
  final String? existingRoute;
  final List<FeatureField> fields;
  final List<String> sections;
  final List<String> capabilities;
  final String? primaryAction;
  final String? emptyLabel;
  final String? sourceDetail;
  final bool listMode;
  final String? dataSourceId;
  final String? createAction;
  final String? recordTitleField;
  final List<String> recordDescriptionFields;
  final HardwareSimulationKind? simulation;
  final String? simulationTargetField;
  final String? successTitle;
  final String? successDescription;
  final AuditExportKind? auditExport;
}

const adminFeatures = <FeatureDefinition>[
  FeatureDefinition(
    id: 'painel-financeiro',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Financeiro e operacional',
    objective:
        'Consolidar resultados financeiros, custos e produção por período.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/financeiro',
  ),
  FeatureDefinition(
    id: 'painel-pecuario',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Dashboard pecuário',
    objective: 'Acompanhar estoque atual e desempenho do rebanho.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/pecuaria',
  ),
  FeatureDefinition(
    id: 'lotacao-currais',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Lotação de currais',
    objective: 'Supervisionar ocupação, capacidade e alertas dos currais.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/confinamento',
  ),
  FeatureDefinition(
    id: 'ativos',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Ativos e depreciação',
    objective: 'Acompanhar patrimônio, manutenção e valor residual.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/ativos',
  ),
  FeatureDefinition(
    id: 'suprimentos',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Suprimentos',
    objective: 'Comparar cotações e apoiar decisões de compra.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/suprimentos',
  ),
  FeatureDefinition(
    id: 'analise-uso',
    profile: FeatureProfile.administration,
    group: 'Painéis de decisão',
    title: 'Análise de uso',
    objective: 'Supervisionar usuários ativos e utilização por fazenda.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/uso',
  ),
  FeatureDefinition(
    id: 'consultas-gerenciais',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Consultas gerenciais',
    objective: 'Consultar lotes, estoque e pesagens sem permitir alterações.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/dashboards/consultas',
  ),
  FeatureDefinition(
    id: 'areas',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Áreas cadastradas',
    objective: 'Consultar as áreas usadas pelos processos da fazenda.',
    status: FeatureStatus.ready,
    emptyLabel: 'Nenhuma área encontrada para os filtros atuais.',
    sourceDetail:
        'A consulta usa os mesmos registros criados no ambiente operacional.',
    listMode: true,
    dataSourceId: 'cadastrar-area',
  ),
  FeatureDefinition(
    id: 'saldo-estoque',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Saldo de estoque',
    objective: 'Consultar o saldo disponível dos itens armazenados.',
    status: FeatureStatus.ready,
    emptyLabel: 'Nenhum item de estoque encontrado.',
    sourceDetail:
        'Consulta demonstrativa consolidada por item e local de armazenamento.',
    listMode: true,
  ),
  FeatureDefinition(
    id: 'processamentos',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Processamentos pecuários',
    objective: 'Acompanhar rotinas pendentes e concluídas.',
    status: FeatureStatus.ready,
    sections: ['Pendentes', 'Concluídos'],
    emptyLabel: 'Nenhum processamento pendente.',
    listMode: true,
  ),
  FeatureDefinition(
    id: 'exportar-log-estoque',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Exportar log de estoque',
    objective: 'Exportar registros de auditoria relacionados ao estoque.',
    status: FeatureStatus.ready,
    sourceDetail:
        'Período e formatos CSV/JSON são premissas funcionais do protótipo frontend.',
    auditExport: AuditExportKind.estoque,
  ),
  FeatureDefinition(
    id: 'exportar-log-pecuaria',
    profile: FeatureProfile.administration,
    group: 'Consultas e auditoria',
    title: 'Exportar log da pecuária',
    objective: 'Exportar o histórico de eventos e movimentações do rebanho.',
    status: FeatureStatus.ready,
    sourceDetail:
        'Período e formatos CSV/JSON são premissas funcionais do protótipo frontend.',
    auditExport: AuditExportKind.pecuaria,
  ),
];

const operationalFeatures = <FeatureDefinition>[
  FeatureDefinition(
    id: 'cadastrar-area',
    profile: FeatureProfile.operational,
    group: 'Cadastros',
    title: 'Áreas',
    objective: 'Cadastrar áreas usadas nos processos da fazenda.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'nome',
        label: 'Nome da área',
        isRequired: true,
        placeholder: 'Ex.: Talhão 03',
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo de uso',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Agricultura', 'Pecuária', 'Fruticultura', 'Reserva'],
      ),
      FeatureField(
        id: 'area-total',
        label: 'Área total',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'unidade',
        label: 'Unidade',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['ha', 'm²'],
      ),
      FeatureField(
        id: 'localizacao',
        label: 'Localização',
        isRequired: true,
        placeholder: 'Setor ou referência',
      ),
      FeatureField(
        id: 'cultura',
        label: 'Cultura / cobertura',
        placeholder: 'Opcional',
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
        placeholder: 'Informações adicionais',
      ),
    ],
    primaryAction: 'Salvar área',
    listMode: true,
    createAction: 'Adicionar área',
    recordTitleField: 'nome',
    recordDescriptionFields: ['tipo', 'area-total', 'unidade'],
  ),
  FeatureDefinition(
    id: 'formulacoes',
    profile: FeatureProfile.operational,
    group: 'Estoque',
    title: 'Formulações',
    objective: 'Criar formulações compostas por matérias-primas e percentuais.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'ativo',
        label: 'Ativo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Sim', 'Não'],
      ),
      FeatureField(
        id: 'produto',
        label: 'Produto',
        isRequired: true,
        placeholder: 'Selecione ou busque o produto',
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de referência',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'unidade',
        label: 'Unidade de medida',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['kg', 't', 'L'],
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Estoque', 'Formulação'],
      ),
      FeatureField(
        id: 'materia-prima',
        label: 'Matéria-prima',
        isRequired: true,
      ),
      FeatureField(
        id: 'porcentagem',
        label: 'Porcentagem (%)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
    ],
    sections: ['Matérias-primas'],
    primaryAction: 'Salvar formulação',
    listMode: true,
    createAction: 'Nova formulação',
    recordTitleField: 'produto',
    recordDescriptionFields: ['quantidade', 'unidade', 'ativo'],
  ),
  FeatureDefinition(
    id: 'batidas',
    profile: FeatureProfile.operational,
    group: 'Estoque',
    title: 'Batida',
    objective:
        'Registrar a produção de uma formulação para um armazém de destino.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Estoque', 'Formulação'],
      ),
      FeatureField(
        id: 'armazem',
        label: 'Armazém de destino',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Armazém A', 'Depósito B', 'Farmácia'],
      ),
      FeatureField(id: 'produto', label: 'Produto', isRequired: true),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de referência',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'unidade',
        label: 'Unidade de medida',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['kg', 't', 'L'],
      ),
    ],
    primaryAction: 'Salvar batida',
    emptyLabel: 'Nenhuma batida registrada.',
    listMode: true,
    createAction: 'Nova batida',
    recordTitleField: 'produto',
    recordDescriptionFields: ['quantidade', 'unidade', 'armazem'],
  ),
  FeatureDefinition(
    id: 'conexao-aparelhos',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Conexão de aparelhos',
    objective: 'Conectar balança e equipamentos externos por Bluetooth.',
    status: FeatureStatus.hardware,
    capabilities: [
      'Bluetooth',
      'Localização',
      'Busca de dispositivos',
      'Permissão durante o uso',
    ],
    primaryAction: 'Concluir configuração',
    simulation: HardwareSimulationKind.devices,
    successTitle: 'Aparelhos conectados no protótipo',
    successDescription:
        'A balança e o equipamento externo estão disponíveis para os fluxos simulados desta sessão.',
  ),
  FeatureDefinition(
    id: 'carga',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Carga',
    objective: 'Executar o fluxo operacional de carregamento do misturador.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'formulacao',
        label: 'Formulação / produto',
        isRequired: true,
      ),
      FeatureField(id: 'origem', label: 'Armazém de origem', isRequired: true),
      FeatureField(
        id: 'equipamento',
        label: 'Misturador / equipamento',
        isRequired: true,
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'unidade',
        label: 'Unidade',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['kg', 't'],
      ),
    ],
    primaryAction: 'Registrar carga',
    sourceDetail:
        'A fonte mostrou apenas a entrada; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova carga',
    recordTitleField: 'formulacao',
    recordDescriptionFields: ['quantidade', 'unidade', 'equipamento'],
  ),
  FeatureDefinition(
    id: 'descarga',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Descarga',
    objective: 'Executar o fluxo operacional de descarga do misturador.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'produto', label: 'Produto carregado', isRequired: true),
      FeatureField(
        id: 'destino',
        label: 'Área / cocho de destino',
        isRequired: true,
      ),
      FeatureField(
        id: 'equipamento',
        label: 'Misturador / equipamento',
        isRequired: true,
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade descarregada',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'unidade',
        label: 'Unidade',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['kg', 't'],
      ),
    ],
    primaryAction: 'Registrar descarga',
    sourceDetail:
        'A fonte mostrou apenas a entrada; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova descarga',
    recordTitleField: 'destino',
    recordDescriptionFields: ['produto', 'quantidade', 'unidade'],
  ),
  FeatureDefinition(
    id: 'balanca',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Balança',
    objective: 'Obter dados de pesagem do equipamento conectado.',
    status: FeatureStatus.hardware,
    capabilities: ['Bluetooth', 'Balança'],
    primaryAction: 'Confirmar leitura',
    simulation: HardwareSimulationKind.scale,
    successTitle: 'Leitura de balança confirmada',
    successDescription:
        'O peso simulado foi capturado e pode ser usado na apresentação do fluxo.',
  ),
  FeatureDefinition(
    id: 'nota-cocho',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Nota de cocho',
    objective: 'Registrar e consultar a nota de cocho.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(id: 'lote', label: 'Lote / curral', isRequired: true),
      FeatureField(
        id: 'nota',
        label: 'Nota de cocho',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          '0 — Limpo',
          '1 — Baixo',
          '2 — Adequado',
          '3 — Sobra moderada',
          '4 — Sobra alta',
        ],
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    primaryAction: 'Salvar nota',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova nota de cocho',
    recordTitleField: 'lote',
    recordDescriptionFields: ['nota', 'data'],
  ),
  FeatureDefinition(
    id: 'configuracoes-misturador',
    profile: FeatureProfile.operational,
    group: 'Misturador',
    title: 'Configurações',
    objective: 'Parametrizar recursos do misturador.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'nome', label: 'Nome da configuração', isRequired: true),
      FeatureField(
        id: 'unidade',
        label: 'Unidade padrão',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['kg', 't'],
      ),
      FeatureField(
        id: 'tolerancia',
        label: 'Tolerância de pesagem (%)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'alerta',
        label: 'Alertas sonoros',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Ativados', 'Desativados'],
      ),
    ],
    primaryAction: 'Salvar configuração',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os parâmetros são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova configuração',
    recordTitleField: 'nome',
    recordDescriptionFields: ['unidade', 'tolerancia', 'alerta'],
  ),
  FeatureDefinition(
    id: 'apontamento',
    profile: FeatureProfile.operational,
    group: 'Agricultura',
    title: 'Apontamento agrícola',
    objective: 'Registrar uma operação agrícola e os recursos associados.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'area',
        label: 'Área',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Talhão 01', 'Talhão 02', 'Pasto Norte'],
      ),
      FeatureField(id: 'operacao', label: 'Operação', isRequired: true),
      FeatureField(id: 'atividade', label: 'Atividade', isRequired: true),
      FeatureField(
        id: 'area-total',
        label: 'Área total',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'area-utilizada',
        label: 'Área utilizada',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'armazem-insumo',
        label: 'Armazém de insumo',
        type: FeatureFieldType.select,
        options: ['Armazém A', 'Depósito B'],
      ),
      FeatureField(
        id: 'armazem-producao',
        label: 'Armazém de produção',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Armazém A', 'Depósito B'],
      ),
    ],
    sections: [
      'Insumos',
      'Abastecimentos',
      'Máquinas / Implementos',
      'Mão de obra / Serviços',
      'Ocorrências',
      'Produção',
    ],
    primaryAction: 'Salvar apontamento',
    listMode: true,
    createAction: 'Novo apontamento',
    recordTitleField: 'atividade',
    recordDescriptionFields: ['operacao', 'area', 'area-utilizada'],
  ),
  FeatureDefinition(
    id: 'marcacao',
    profile: FeatureProfile.operational,
    group: 'Agricultura',
    title: 'Marcação',
    objective: 'Acessar e registrar marcações agrícolas.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'area', label: 'Área', isRequired: true),
      FeatureField(
        id: 'tipo',
        label: 'Tipo de marcação',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          'Ponto de atenção',
          'Amostragem',
          'Ocorrência',
          'Limite de operação',
        ],
      ),
      FeatureField(id: 'descricao', label: 'Descrição', isRequired: true),
      FeatureField(
        id: 'referencia',
        label: 'Referência de localização',
        isRequired: true,
      ),
    ],
    primaryAction: 'Salvar marcação',
    sourceDetail:
        'Os campos não foram exibidos; o protótipo usa premissas mínimas sem GPS real.',
    listMode: true,
    createAction: 'Nova marcação',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['tipo', 'area', 'referencia'],
  ),
  FeatureDefinition(
    id: 'colheita-frutas',
    profile: FeatureProfile.operational,
    group: 'Agricultura',
    title: 'Colheita de frutas',
    objective: 'Registrar motorista, veículo e caixas da colheita.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(id: 'placa', label: 'Placa', isRequired: true),
      FeatureField(id: 'motorista', label: 'Motorista', isRequired: true),
      FeatureField(id: 'cpf', label: 'CPF do motorista', isRequired: true),
      FeatureField(
        id: 'caixas',
        label: 'Caixas (kg)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
    ],
    sections: ['Caixas da colheita'],
    primaryAction: 'Registrar colheita',
  ),
  FeatureDefinition(
    id: 'rebanho-inicial',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Rebanho inicial',
    objective: 'Estabelecer a composição inicial do rebanho.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data de referência',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'especie',
        label: 'Espécie',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Bovino', 'Bubalino', 'Ovino'],
      ),
      FeatureField(
        id: 'categoria',
        label: 'Categoria',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Bezerro', 'Novilha', 'Vaca', 'Boi'],
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de animais',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'area',
        label: 'Área / módulo inicial',
        isRequired: true,
      ),
      FeatureField(
        id: 'peso-medio',
        label: 'Peso médio (kg)',
        type: FeatureFieldType.number,
      ),
    ],
    primaryAction: 'Cadastrar rebanho',
    sourceDetail:
        'Os campos internos não foram exibidos; o protótipo usa a composição mínima necessária para iniciar o rebanho.',
    listMode: true,
    createAction: 'Nova composição inicial',
    recordTitleField: 'categoria',
    recordDescriptionFields: ['quantidade', 'especie', 'area'],
  ),
  FeatureDefinition(
    id: 'conexao-aparelhos-pecuaria',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Conexão de aparelhos',
    objective: 'Preparar balança e leitor RFID para as rotinas pecuárias.',
    status: FeatureStatus.hardware,
    capabilities: ['Bluetooth', 'Localização', 'Balança', 'RFID'],
    primaryAction: 'Concluir configuração',
    simulation: HardwareSimulationKind.devices,
    successTitle: 'Aparelhos pecuários conectados',
    successDescription:
        'A balança e o leitor RFID estão conectados na simulação desta sessão.',
  ),
  FeatureDefinition(
    id: 'lote-animais',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Lote de animais',
    objective: 'Criar um lote em fluxo de múltiplas etapas.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'especie',
        label: 'Espécie',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Bovino', 'Bubalino', 'Ovino'],
      ),
      FeatureField(id: 'descricao', label: 'Descrição', isRequired: true),
      FeatureField(
        id: 'categoria',
        label: 'Categoria',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Bezerro', 'Novilha', 'Vaca', 'Boi'],
      ),
    ],
    primaryAction: 'Criar lote',
    listMode: true,
    createAction: 'Novo lote',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['especie', 'categoria'],
  ),
  FeatureDefinition(
    id: 'registrar-animal',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Registrar animal',
    objective: 'Cadastrar um animal individualmente.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(id: 'categoria', label: 'Categoria', isRequired: true),
      FeatureField(id: 'raca', label: 'Raça', isRequired: true),
      FeatureField(
        id: 'nascimento',
        label: 'Data de nascimento',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'peso',
        label: 'Peso (kg)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'preco-kg',
        label: 'Preço do kg vivo',
        type: FeatureFieldType.number,
      ),
    ],
    primaryAction: 'Registrar animal',
    listMode: true,
    createAction: 'Novo animal',
    recordTitleField: 'categoria',
    recordDescriptionFields: ['raca', 'peso', 'nascimento'],
  ),
  FeatureDefinition(
    id: 'pesagem',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Pesagens',
    objective: 'Consultar e registrar pesagens do rebanho.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/campo/pesagem',
  ),
  FeatureDefinition(
    id: 'transferencia-animal',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Transferência animal / lote',
    objective:
        'Mover um animal para outro lote com identificação por brinco, RFID ou câmera.',
    status: FeatureStatus.hardware,
    fields: [
      FeatureField(
        id: 'identificacao',
        label: 'Identificação animal',
        isRequired: true,
        placeholder: 'Brinco ou ID',
      ),
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'lote-atual', label: 'Lote atual', isRequired: true),
      FeatureField(id: 'novo-lote', label: 'Novo lote', isRequired: true),
    ],
    capabilities: ['Balança', 'RFID', 'Scanner SISBOV'],
    primaryAction: 'Salvar transferência',
    listMode: true,
    createAction: 'Nova transferência de animal',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['lote-atual', 'novo-lote'],
    simulation: HardwareSimulationKind.rfid,
    simulationTargetField: 'identificacao',
  ),
  FeatureDefinition(
    id: 'scanner-sisbov',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Scanner SISBOV',
    objective: 'Capturar a identificação do animal usando a câmera.',
    status: FeatureStatus.hardware,
    capabilities: ['Câmera', 'Área de enquadramento', 'Reiniciar leitura'],
    primaryAction: 'Usar identificação capturada',
    simulation: HardwareSimulationKind.scanner,
    successTitle: 'Identificação SISBOV capturada',
    successDescription:
        'O código simulado está disponível para identificação do animal nesta sessão.',
  ),
  FeatureDefinition(
    id: 'transferencia-lote-area',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Transferência lote / área',
    objective: 'Alterar a localização de um lote entre área e módulo.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'lote', label: 'Lote', isRequired: true),
      FeatureField(
        id: 'local-atual',
        label: 'Área / módulo atual',
        isRequired: true,
      ),
      FeatureField(id: 'area', label: 'Nova área', isRequired: true),
      FeatureField(id: 'modulo', label: 'Novo módulo', isRequired: true),
    ],
    primaryAction: 'Salvar transferência',
    listMode: true,
    createAction: 'Nova transferência',
    recordTitleField: 'lote',
    recordDescriptionFields: ['area', 'modulo'],
  ),
  FeatureDefinition(
    id: 'nascimentos',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Nascimentos',
    objective: 'Registrar nascimento de animais.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/campo/ciclo',
  ),
  FeatureDefinition(
    id: 'mortes',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Mortes',
    objective: 'Consultar e registrar mortes do rebanho.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/campo/ciclo',
  ),
  FeatureDefinition(
    id: 'perdas',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Perdas',
    objective: 'Registrar perdas após identificar o animal.',
    status: FeatureStatus.hardware,
    fields: [
      FeatureField(
        id: 'identificacao',
        label: 'Identificação animal',
        isRequired: true,
        placeholder: 'Brinco ou ID',
      ),
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data da ocorrência',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(id: 'lote', label: 'Lote atual', isRequired: true),
      FeatureField(id: 'causa', label: 'Motivo da perda', isRequired: true),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    capabilities: ['Balança', 'RFID', 'Scanner SISBOV'],
    primaryAction: 'Registrar perda',
    sourceDetail:
        'A fonte mostrou apenas a identificação; os campos posteriores são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova perda',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['causa', 'lote', 'data'],
    simulation: HardwareSimulationKind.rfid,
    simulationTargetField: 'identificacao',
  ),
  FeatureDefinition(
    id: 'compras-animais',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Compra de animais',
    objective: 'Consultar e registrar compras de animais.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'fornecedor', label: 'Fornecedor', isRequired: true),
      FeatureField(
        id: 'data',
        label: 'Data da compra',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'especie',
        label: 'Espécie',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Bovino', 'Bubalino', 'Ovino'],
      ),
      FeatureField(id: 'categoria', label: 'Categoria', isRequired: true),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de animais',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'valor-total',
        label: 'Valor total (R\$)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'documento',
        label: 'Nota / documento de origem',
        isRequired: true,
      ),
    ],
    primaryAction: 'Registrar compra',
    emptyLabel: 'Nenhuma compra de animais registrada.',
    sourceDetail:
        'O formulário não foi aberto; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova compra',
    recordTitleField: 'fornecedor',
    recordDescriptionFields: ['quantidade', 'categoria', 'data'],
  ),
  FeatureDefinition(
    id: 'vendas',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Vendas',
    objective: 'Registrar vendas de animais com documentos e frete.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/campo/venda',
  ),
  FeatureDefinition(
    id: 'nutricoes',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Nutrições',
    objective: 'Registrar produtos, quantidade, área, módulo e cocho.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/campo/arracoamento',
  ),
  FeatureDefinition(
    id: 'sanitario',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Sanitário',
    objective: 'Criar um manejo sanitário por responsável e lote.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'lote', label: 'Lote', isRequired: true),
      FeatureField(
        id: 'data',
        label: 'Data do manejo',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo de manejo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Vacinação', 'Vermifugação', 'Tratamento', 'Exame'],
      ),
      FeatureField(
        id: 'produto',
        label: 'Produto / procedimento',
        isRequired: true,
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    primaryAction: 'Salvar manejo',
    sourceDetail:
        'A fonte mostrou apenas a primeira etapa; os campos complementares são premissas do protótipo frontend.',
    listMode: true,
    createAction: 'Novo manejo sanitário',
    recordTitleField: 'lote',
    recordDescriptionFields: ['tipo', 'data'],
  ),
  FeatureDefinition(
    id: 'desmama',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Desmama',
    objective: 'Registrar desmama e identificar vacas paridas.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Convencional', 'Precoce', 'Temporária'],
      ),
      FeatureField(id: 'lote', label: 'Lote', isRequired: true),
      FeatureField(
        id: 'identificacao',
        label: 'Identificação das vacas paridas',
        isRequired: true,
      ),
    ],
    sections: ['Identificações adicionais'],
    primaryAction: 'Salvar desmama',
    listMode: true,
    createAction: 'Nova desmama',
    recordTitleField: 'lote',
    recordDescriptionFields: ['tipo', 'identificacao'],
  ),
  FeatureDefinition(
    id: 'apartacao',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Apartação',
    objective: 'Executar e registrar a apartação do rebanho.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'lote-origem',
        label: 'Lote de origem',
        isRequired: true,
      ),
      FeatureField(
        id: 'criterio',
        label: 'Critério',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Peso', 'Categoria', 'Sexo', 'Condição corporal'],
      ),
      FeatureField(
        id: 'lote-destino',
        label: 'Lote de destino',
        isRequired: true,
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de animais',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
    ],
    primaryAction: 'Registrar apartação',
    sourceDetail:
        'Os campos não foram exibidos; o protótipo usa premissas operacionais mínimas.',
    listMode: true,
    createAction: 'Nova apartação',
    recordTitleField: 'lote-origem',
    recordDescriptionFields: ['criterio', 'lote-destino', 'quantidade'],
  ),
  FeatureDefinition(
    id: 'localizar-animal',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Localizar animal',
    objective: 'Localizar um animal por brinco, ID, RFID ou câmera.',
    status: FeatureStatus.hardware,
    fields: [
      FeatureField(
        id: 'identificacao',
        label: 'Identificação animal',
        isRequired: true,
        placeholder: 'Brinco ou ID',
      ),
    ],
    capabilities: ['RFID', 'Scanner SISBOV'],
    primaryAction: 'Buscar animal',
    simulation: HardwareSimulationKind.rfid,
    simulationTargetField: 'identificacao',
    successTitle: 'Animal localizado',
    successDescription:
        'Animal ativo no Lote 42 · Engorda, atualmente no Pasto Norte · Módulo A.',
  ),
  FeatureDefinition(
    id: 'pastagens',
    profile: FeatureProfile.operational,
    group: 'Pecuária',
    title: 'Pastagens',
    objective: 'Registrar recursos e serviços aplicados à pastagem.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'armazem-insumos',
        label: 'Armazém de insumos',
        isRequired: true,
      ),
      FeatureField(
        id: 'armazem-producao',
        label: 'Armazém de produção',
        isRequired: true,
      ),
    ],
    sections: ['Insumos', 'Abastecimentos', 'Máquinas / Equipamentos'],
    primaryAction: 'Salvar pastagem',
    listMode: true,
    createAction: 'Novo manejo de pastagem',
    recordTitleField: 'armazem-producao',
    recordDescriptionFields: ['armazem-insumos', 'responsavel'],
  ),
  FeatureDefinition(
    id: 'estacao-monta',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Estação de monta',
    objective: 'Gerenciar períodos e ciclos de reprodução.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'nome', label: 'Nome da estação', isRequired: true),
      FeatureField(
        id: 'inicio',
        label: 'Data de início',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'fim',
        label: 'Data de término',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'metodo',
        label: 'Método principal',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          'Monta natural',
          'Inseminação artificial',
          'IATF',
          'Transferência de embrião',
        ],
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    primaryAction: 'Criar estação',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova estação',
    recordTitleField: 'nome',
    recordDescriptionFields: ['metodo', 'inicio', 'fim'],
  ),
  FeatureDefinition(
    id: 'lotes-reproducao',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Lotes / reprodução',
    objective: 'Organizar lotes vinculados ao processo reprodutivo.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'estacao', label: 'Estação de monta', isRequired: true),
      FeatureField(id: 'lote', label: 'Lote', isRequired: true),
      FeatureField(
        id: 'finalidade',
        label: 'Finalidade',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Matrizes', 'Reprodutores', 'Receptoras', 'Novilhas'],
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de animais',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
    ],
    primaryAction: 'Salvar vínculo',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Vincular lote',
    recordTitleField: 'lote',
    recordDescriptionFields: ['finalidade', 'estacao', 'quantidade'],
  ),
  FeatureDefinition(
    id: 'material-reprodutivo',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Touros / sêmen / embrião',
    objective: 'Gerenciar material e recursos reprodutivos.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo de recurso',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Touro', 'Sêmen', 'Embrião'],
      ),
      FeatureField(
        id: 'identificacao',
        label: 'Identificação / código',
        isRequired: true,
      ),
      FeatureField(id: 'raca', label: 'Raça', isRequired: true),
      FeatureField(
        id: 'fornecedor',
        label: 'Fornecedor / origem',
        isRequired: true,
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade disponível',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
    ],
    primaryAction: 'Cadastrar recurso',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Novo recurso',
    recordTitleField: 'identificacao',
    recordDescriptionFields: ['tipo', 'raca', 'quantidade'],
  ),
  FeatureDefinition(
    id: 'protocolos-estacao',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Protocolos / estação',
    objective: 'Gerenciar protocolos associados à estação reprodutiva.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(id: 'nome', label: 'Nome do protocolo', isRequired: true),
      FeatureField(id: 'estacao', label: 'Estação de monta', isRequired: true),
      FeatureField(
        id: 'tipo',
        label: 'Tipo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          'IATF',
          'Inseminação',
          'Transferência de embrião',
          'Sincronização de cio',
        ],
      ),
      FeatureField(
        id: 'inicio',
        label: 'Data de início',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
    ],
    sections: ['Etapas do protocolo'],
    primaryAction: 'Salvar protocolo',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Novo protocolo',
    recordTitleField: 'nome',
    recordDescriptionFields: ['tipo', 'estacao', 'inicio'],
  ),
  FeatureDefinition(
    id: 'monta-natural',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Monta natural',
    objective: 'Registrar operações de monta natural.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(id: 'lote', label: 'Lote de matrizes', isRequired: true),
      FeatureField(id: 'touro', label: 'Touro / reprodutor', isRequired: true),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de fêmeas',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    primaryAction: 'Registrar monta',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Nova monta',
    recordTitleField: 'lote',
    recordDescriptionFields: ['touro', 'quantidade', 'data'],
  ),
  FeatureDefinition(
    id: 'diagnostico-gestacao',
    profile: FeatureProfile.operational,
    group: 'Reprodução',
    title: 'Diagnóstico de gestação',
    objective: 'Registrar e consultar diagnósticos de gestação.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data do diagnóstico',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(id: 'lote', label: 'Lote', isRequired: true),
      FeatureField(
        id: 'resultado',
        label: 'Resultado',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Prenhe', 'Vazia', 'Reavaliar'],
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade de animais',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'veterinario',
        label: 'Veterinário responsável',
        isRequired: true,
      ),
    ],
    primaryAction: 'Salvar diagnóstico',
    sourceDetail:
        'A fonte mostrou apenas o acesso; os campos são premissas funcionais do protótipo frontend.',
    listMode: true,
    createAction: 'Novo diagnóstico',
    recordTitleField: 'lote',
    recordDescriptionFields: ['resultado', 'quantidade', 'data'],
  ),
  FeatureDefinition(
    id: 'abastecimentos',
    profile: FeatureProfile.operational,
    group: 'Gestão de frota',
    title: 'Abastecimentos',
    objective: 'Consultar e registrar abastecimentos da frota.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'data',
        label: 'Data',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'veiculo',
        label: 'Veículo / equipamento',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          'Trator John Deere 6110',
          'Colheitadeira CR7',
          'Caminhão Boiadeiro',
          'Pulverizador',
        ],
      ),
      FeatureField(
        id: 'combustivel',
        label: 'Combustível',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Diesel S10', 'Diesel S500', 'Gasolina', 'Etanol'],
      ),
      FeatureField(
        id: 'quantidade',
        label: 'Quantidade (L)',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'medidor',
        label: 'Hodômetro / horímetro',
        type: FeatureFieldType.number,
        isRequired: true,
      ),
      FeatureField(
        id: 'origem',
        label: 'Posto / tanque de origem',
        isRequired: true,
      ),
    ],
    primaryAction: 'Registrar abastecimento',
    emptyLabel: 'Nenhum abastecimento registrado.',
    sourceDetail:
        'Campos complementares adotados como premissa funcional do protótipo frontend.',
    listMode: true,
    createAction: 'Novo abastecimento',
    recordTitleField: 'veiculo',
    recordDescriptionFields: ['quantidade', 'combustivel', 'data'],
  ),
  FeatureDefinition(
    id: 'manutencao-frota',
    profile: FeatureProfile.operational,
    group: 'Gestão de frota',
    title: 'Manutenção',
    objective: 'Controlar manutenções da frota.',
    status: FeatureStatus.ready,
    fields: [
      FeatureField(
        id: 'responsavel',
        label: 'Responsável',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['João Oliveira', 'Maria Souza', 'Carlos Dias'],
      ),
      FeatureField(
        id: 'equipamento',
        label: 'Veículo / equipamento',
        type: FeatureFieldType.select,
        isRequired: true,
        options: [
          'Trator John Deere 6110',
          'Colheitadeira CR7',
          'Caminhão Boiadeiro',
          'Pulverizador',
        ],
      ),
      FeatureField(
        id: 'tipo',
        label: 'Tipo',
        type: FeatureFieldType.select,
        isRequired: true,
        options: ['Preventiva', 'Corretiva', 'Inspeção'],
      ),
      FeatureField(
        id: 'descricao',
        label: 'Serviço',
        isRequired: true,
        placeholder: 'Descreva a manutenção',
      ),
      FeatureField(
        id: 'data',
        label: 'Data prevista',
        type: FeatureFieldType.date,
        isRequired: true,
      ),
      FeatureField(
        id: 'oficina',
        label: 'Oficina / responsável externo',
        isRequired: true,
      ),
      FeatureField(
        id: 'custo',
        label: 'Custo estimado (R\$)',
        type: FeatureFieldType.number,
      ),
      FeatureField(
        id: 'observacao',
        label: 'Observação',
        type: FeatureFieldType.textarea,
      ),
    ],
    primaryAction: 'Programar manutenção',
    listMode: true,
    createAction: 'Nova manutenção',
    recordTitleField: 'descricao',
    recordDescriptionFields: ['tipo', 'equipamento', 'data'],
  ),
  FeatureDefinition(
    id: 'minhas-os',
    profile: FeatureProfile.operational,
    group: 'Ordem de serviço',
    title: 'Minhas OS',
    objective:
        'Consultar ordens de serviço vinculadas ao funcionário e à fazenda.',
    status: FeatureStatus.ready,
    emptyLabel: 'Nenhuma ordem de serviço atribuída.',
    sourceDetail:
        'Consulta demonstrativa das ordens atribuídas ao funcionário e à fazenda ativa.',
    listMode: true,
  ),
  FeatureDefinition(
    id: 'sincronizacao',
    profile: FeatureProfile.operational,
    group: 'Sincronização',
    title: 'Sincronização de dados',
    objective: 'Enviar a fila local para a nuvem após operação offline.',
    status: FeatureStatus.ready,
    existingRoute: '/fazendas/mais/sync',
    capabilities: ['Rebanho', 'Lotes', 'Pesagem', 'Mortes'],
  ),
];

const allFeatures = <FeatureDefinition>[
  ...adminFeatures,
  ...operationalFeatures,
];

FeatureDefinition? featureById(String id) {
  for (final feature in allFeatures) {
    if (feature.id == id) return feature;
  }
  return null;
}
